name: GitHub-Profile-3D-Contrib

on:
  schedule:
    # Runs every day at 18:00 UTC (Adjust if needed)
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME:  ${{ github.repository_owner }}   

      - name: Commit & Push
        run: |
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add -A
            git commit -m "generated" || echo "No changes to commit"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
